version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: images
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  django:
    depends_on:
      - postgres
    build: .
    ports:
      - "80:80"

volumes:
  postgres-db:
    driver: local
