name: Pytest

on:
  pull_request:
    paths:
      - 'src/**'
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'images/**'
      - 'image_app/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Pytest
    env:
      CONFIG: "config.test.json"
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Create json config
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.test.json"
          json: ${{ secrets.CONFIG_TEST_JSON }}
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "^3.11"
      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
      # virtualenv cache should depends on OS, Python version and `poetry.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Run poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.3.1
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        run: |
          ./.venv/bin/pytest
